# Generated by Django 5.1.7 on 2025-03-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('alternative_phone', models.CharField(max_length=15, null=True)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
