# Generated by Django 5.1.7 on 2025-03-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_patientprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('accountant', 'Accountant'), ('receptionist', 'Receptionist'), ('lab_technician', 'Laboratory Technician'), ('pharmacist', 'Pharmacist'), ('staff', 'General Staff')], default='staff', max_length=20),
        ),
    ]
