# Generated by Django 5.1.7 on 2025-04-24 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patients_delete_patient'),
        ('pos', '0002_remove_saledetail_item_saledetail_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='patient',
            field=models.ForeignKey(blank=True, default=1, help_text='The patient associated with this sale; defaults to Walk-in Customer if not specified', null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patients'),
        ),
    ]
