# Generated by Django 5.1.7 on 2025-04-25 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patients_delete_patient'),
        ('pos', '0003_sale_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount applied to the total amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card'), ('MOBILE_PAYMENT', 'Mobile Payment'), ('INSURANCE', 'Insurance')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='The patient associated with this sale; null if not specified', null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patients'),
        ),
    ]
