# Generated by Django 5.1.7 on 2025-04-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_sale_discount_sale_payment_method_sale_status_and_more'),
    ]

    operations = [
    ]
